// =============================================================================
//  Syntax Token System for CodeEditorLib
// =============================================================================
//
//  Description :
//  Defines token types and token objects used by the syntax
//  highlighting engine inside the editor.
//
//  This file is responsible for:
//  - Defining all supported syntax token categories
//  - Representing parsed text tokens from source code
//  - Storing token position and length information
//  - Providing token metadata for rendering and parsing
//  - Supporting multi-language syntax highlighting
//
// -----------------------------------------------------------------------------
//
//  TokenType Enum :
//  Contains all token classifications recognized by the editor.
//
//  Example token categories:
//  - Keywords       -> if, else, class, public
//  - Strings        -> "Hello World"
//  - Comments       -> // comment
//  - Numbers        -> 123, 3.14
//  - Operators      -> +, -, ==
//  - HTML/XML tags  -> <div>, <node>
//  - CSS properties -> color, margin
//  - SQL keywords   -> SELECT, INSERT
//
// -----------------------------------------------------------------------------
//
//  SyntaxToken Class :
//  Represents a single parsed token generated by the lexer
//  or syntax highlighter engine.
//
//  Each token stores:
//  - Start position inside the text buffer
//  - Token length
//  - Token classification type
//  - Original token text
//
//  These tokens are later used for:
//  - Syntax coloring
//  - Text rendering
//  - Code analysis
//  - IntelliSense systems
//  - Parsing and editor features
//
// -----------------------------------------------------------------------------
//
//  Author      : Ari Sohandri Putra
//  Repository  : https://github.com/arisohandriputra/CodeEditorLib
//  License     : MIT License
//  Copyright   : Copyright (c) 2026 Ari Sohandri Putra
//
// -----------------------------------------------------------------------------
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
//  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
//  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// =============================================================================

using System;

namespace CodeEditorLib.Core
{
    public enum TokenType
    {
        Default,
        Keyword,
        String,
        Comment,
        Number,
        Operator,
        Preprocessor,
        Type,
        Identifier,
        Whitespace,
        Delimiter,
        Attribute,
        XmlTag,
        XmlAttribute,
        XmlValue,
        HtmlTag,
        HtmlAttribute,
        HtmlValue,
        CssProperty,
        CssValue,
        CssSelector,
        SqlKeyword,
        SqlFunction
    }

    public class SyntaxToken
    {
        private int _startIndex;
        private int _length;
        private TokenType _tokenType;
        private string _text;

        public SyntaxToken(int startIndex, int length, TokenType tokenType, string text)
        {
            _startIndex = startIndex;
            _length = length;
            _tokenType = tokenType;
            _text = text;
        }

        public int StartIndex { get { return _startIndex; } }

        public int Length { get { return _length; } }

        public int EndIndex { get { return _startIndex + _length; } }

        public TokenType TokenType { get { return _tokenType; } }

        public string Text { get { return _text; } }

        public override string ToString()
        {
            return string.Format("[{0}] '{1}' @ {2}+{3}", _tokenType, _text, _startIndex, _length);
        }
    }
}
