'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = True          ' <-- satu instance saja
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.CE__.Form1
        End Sub

        ' ---------------------------------------------------------------
        ' Dipanggil ketika user double-klik file SAAT program sudah jalan.
        ' Argumen baris perintah diteruskan ke Form1 yang sedang berjalan.
        ' ---------------------------------------------------------------
        Protected Overrides Sub OnStartupNextInstance(
                ByVal eventArgs As Global.Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs)

            MyBase.OnStartupNextInstance(eventArgs)

            ' Ambil Form1 dari MainForm dan panggil method publik-nya
            Dim mainForm = TryCast(Me.MainForm, Global.CE__.Form1)
            If mainForm IsNot Nothing Then
                ' Bawa window ke depan jika sedang minimize / di belakang
                If mainForm.WindowState = System.Windows.Forms.FormWindowState.Minimized Then
                    mainForm.WindowState = System.Windows.Forms.FormWindowState.Normal
                End If
                mainForm.Activate()

                ' Buka setiap file yang dikirim sebagai argumen
                For Each arg As String In eventArgs.CommandLine
                    If System.IO.File.Exists(arg) Then
                        mainForm.OpenFileFromArgs(arg)
                    End If
                Next
            End If
        End Sub

    End Class
End Namespace
